---
title: "Unit 5 Text_1"
output:
  html_document:
    keep_md: true
---




```{r}
library(dplyr)
library(tidyr)
library(caret)
library(tm)
library(SnowballC)
library(caTools)
library(rpart)
library(rpart.plot)

```
## Prepare Corpus ##
```{r}
df<-read.csv('Unit5_1/tweets.csv',stringsAsFactors = FALSE)

df<- df %>% mutate(negative = Avg<=-1)
table(df$negative)
corpus <- Corpus(VectorSource(df$Tweet))
corpus[[1]]$content


# Convert to lower-case

corpus = tm_map(corpus, content_transformer(tolower))

corpus[[1]]$content

# Remove punctuation

corpus = tm_map(corpus, removePunctuation)

corpus[[1]]$content

# Look at stop words 
stopwords("english")[1:10]

# Remove stopwords and apple

corpus = tm_map(corpus, removeWords, c("apple", stopwords("english")))

corpus[[1]]$content

# Stem document 

corpus = tm_map(corpus, stemDocument)

corpus[[1]]$content

```
## Create Frequency Matrix
```{r}
frequencies <- DocumentTermMatrix(corpus)

findFreqTerms(frequencies,lowfreq =100)

sparse = removeSparseTerms(frequencies,sparse = .995)
dim(sparse)

tweetsSpares <- as.data.frame(as.matrix(sparse))

#clean column names (always do when using text as dataframe columns)
colnames(tweetsSpares)<- make.names(colnames(tweetsSpares))

tweetsSpares$Negative <- df$negative

table(tweetsSpares$Negative)
```
## Split dataset ##
```{r}
set.seed(123)

splt = sample.split(tweetsSpares$Negative,SplitRatio = 0.7)
df_train <- tweetsSpares[splt,]
df_test <- tweetsSpares[!splt,]
```
## Create a CART Model ##
```{r}
CART_model <- rpart(Negative ~ ., data=df_train, method='class')

prp(CART_model)

prediction_CART<- predict(CART_model,newdata = df_test,type='class')
head(prediction_CART)

CM<-table(df_test$Negative,prediction_CART)
CM
sum(diag(CM))/sum(CM)
```
## Compare CART with Baseline ##
```{r}
CM
sum(CM[1,])/sum(CM)
```

## With Random Forest ##
```{r}
set.seed(123)
RDF<- randomForest::randomForest(Negative ~.,data=df_train)

prediction_RDF<- predict(RDF,newdata = df_test)


CM<-table(df_test$Negative,prediction_RDF>0.5)
CM
sum(diag(CM))/sum(CM)
```
## Logistics Model ##
```{r}
lm<-glm(Negative~.,data=df_train,family='binomial')
prediction_LM<- predict(lm,newdata = df_test,type='response')


CM<-table(df_test$Negative,prediction_LM>0.5)
CM
sum(diag(CM))/sum(CM)


```

